### ISSUE TITLE
Filter string does not map correctly when it contains special characters

### ISSUE THREAD

**Issue by azzlack** [azzlack/Microsoft.AspNet.OData.Extensions.ODataQueryMapper#1]
I.e. `$filter=tolower(Name) eq 'Test & test'` becomes `$filter=tolower(Name) eq 'Test `

See https://msdn.microsoft.com/en-us/library/aa226544(SQL.80).aspx for all characters

**Comment by azzlack** [comment]
```
2016-01-26 17:43:40,179 [8000018e-0007-ff00-b63f-84710c7967bb][ovea][18] ERROR ExceptionHandler - Microsoft.OData.Core.ODataException: There is an unterminated string literal at position 46 in 'KundeID eq ' MENO' and tolower(Navn) eq 'test '.
   at Microsoft.OData.Core.UriParser.ExpressionLexer.NextToken()
   at Microsoft.OData.Core.UriParser.Parsers.UriQueryExpressionParser.ParseComparison()
   at Microsoft.OData.Core.UriParser.Parsers.UriQueryExpressionParser.ParseLogicalAnd()
   at Microsoft.OData.Core.UriParser.Parsers.UriQueryExpressionParser.ParseLogicalOr()
   at Microsoft.OData.Core.UriParser.Parsers.UriQueryExpressionParser.ParseExpression()
   at Microsoft.OData.Core.UriParser.Parsers.UriQueryExpressionParser.ParseExpressionText(String expressionText)
   at Microsoft.OData.Core.UriParser.Parsers.UriQueryExpressionParser.ParseFilter(String filter)
   at Microsoft.OData.Core.UriParser.ODataQueryOptionParser.ParseFilterImplementation(String filter, ODataUriParserConfiguration configuration, IEdmType elementType, IEdmNavigationSource navigationSource)
   at Microsoft.OData.Core.UriParser.ODataQueryOptionParser.ParseFilter()
   at System.Web.OData.Query.FilterQueryOption.get_FilterClause()
   at System.Web.OData.Query.Validators.FilterQueryValidator.Validate(FilterQueryOption filterQueryOption, ODataValidationSettings settings)
   at System.Web.OData.Query.FilterQueryOption.Validate(ODataValidationSettings validationSettings)
   at System.Web.OData.Query.Validators.ODataQueryValidator.Validate(ODataQueryOptions options, ODataValidationSettings validationSettings)
   at System.Web.OData.Query.ODataQueryOptions.Validate(ODataValidationSettings validationSettings)
   at Microsoft.AspNet.OData.Extensions.ODataQueryMapper.ODataQuery`1.ValidateQuery()
   at Microsoft.AspNet.OData.Extensions.ODataQueryMapper.ODataQuery`1.ApplyTo(IQueryable`1 collection)
```
